trigger:
- main

pool:
  name: Default # 🔁 Nome do agent pool
  demands:
    - Agent.Name -equals agentnuvem2  # 🔁 Força o uso do agente específico - informar o nome do Agente criado
  vmImage: 'windows-latest'

variables:
  resourceGroupName: rg-iac-webapp
  location: centralus
  templateFile: arm-templates/webapp-template.json
  parametersFile: arm-templates/webapp-parameters.json

stages:
- stage: DeployInfrastructure
  jobs:
  - job: ARM_Deployment
    steps:
    - task: AzureResourceManagerTemplateDeployment@3
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: 'mbanuvem' # 🔁 informar o nome do Service Connection criado
        subscriptionId: 'ba52c3d7-8bb5-4526-a2bc-41335fa2c375' # 🔁 substituir pelo ID da subscription Azure
        action: 'Create Or Update Resource Group'
        resourceGroupName: '$(resourceGroupName)'
        location: '$(location)'
        templateLocation: 'Linked artifact'
        csmFile: '$(templateFile)'
        csmParametersFile: '$(parametersFile)'
        deploymentMode: 'Incremental'

- stage: DeployApp
  dependsOn: DeployInfrastructure
  jobs:
  - job: Publish_HTML
    steps:
    - task: AzureWebApp@1
      inputs:
        azureSubscription: 'mbanuvem' # 🔁 informar o nome do Service Connection criado
        appType: 'webApp'
        appName: 'mbanuvem001'
        package: 'src'
